// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/flux.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeploymentPackage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FunctionName  string                 `protobuf:"bytes,1,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	CodeArchive   []byte                 `protobuf:"bytes,2,opt,name=code_archive,json=codeArchive,proto3" json:"code_archive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploymentPackage) Reset() {
	*x = DeploymentPackage{}
	mi := &file_proto_flux_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentPackage) ProtoMessage() {}

func (x *DeploymentPackage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flux_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentPackage.ProtoReflect.Descriptor instead.
func (*DeploymentPackage) Descriptor() ([]byte, []int) {
	return file_proto_flux_proto_rawDescGZIP(), []int{0}
}

func (x *DeploymentPackage) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *DeploymentPackage) GetCodeArchive() []byte {
	if x != nil {
		return x.CodeArchive
	}
	return nil
}

type DeploymentAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploymentAck) Reset() {
	*x = DeploymentAck{}
	mi := &file_proto_flux_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentAck) ProtoMessage() {}

func (x *DeploymentAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flux_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentAck.ProtoReflect.Descriptor instead.
func (*DeploymentAck) Descriptor() ([]byte, []int) {
	return file_proto_flux_proto_rawDescGZIP(), []int{1}
}

func (x *DeploymentAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeploymentAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FunctionConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Handler        string                 `protobuf:"bytes,2,opt,name=handler,proto3" json:"handler,omitempty"`
	CpuMillicores  int32                  `protobuf:"varint,3,opt,name=cpu_millicores,json=cpuMillicores,proto3" json:"cpu_millicores,omitempty"`
	MemoryMb       int64                  `protobuf:"varint,4,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FunctionConfig) Reset() {
	*x = FunctionConfig{}
	mi := &file_proto_flux_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionConfig) ProtoMessage() {}

func (x *FunctionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flux_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionConfig.ProtoReflect.Descriptor instead.
func (*FunctionConfig) Descriptor() ([]byte, []int) {
	return file_proto_flux_proto_rawDescGZIP(), []int{2}
}

func (x *FunctionConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionConfig) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

func (x *FunctionConfig) GetCpuMillicores() int32 {
	if x != nil {
		return x.CpuMillicores
	}
	return 0
}

func (x *FunctionConfig) GetMemoryMb() int64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *FunctionConfig) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type FunctionAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionAck) Reset() {
	*x = FunctionAck{}
	mi := &file_proto_flux_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionAck) ProtoMessage() {}

func (x *FunctionAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flux_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionAck.ProtoReflect.Descriptor instead.
func (*FunctionAck) Descriptor() ([]byte, []int) {
	return file_proto_flux_proto_rawDescGZIP(), []int{3}
}

func (x *FunctionAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FunctionAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FunctionName  string                 `protobuf:"bytes,1,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	Input         []byte                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionRequest) Reset() {
	*x = ExecutionRequest{}
	mi := &file_proto_flux_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionRequest) ProtoMessage() {}

func (x *ExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flux_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionRequest.ProtoReflect.Descriptor instead.
func (*ExecutionRequest) Descriptor() ([]byte, []int) {
	return file_proto_flux_proto_rawDescGZIP(), []int{4}
}

func (x *ExecutionRequest) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *ExecutionRequest) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

type ExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        []byte                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	DurationMs    int64                  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionResponse) Reset() {
	*x = ExecutionResponse{}
	mi := &file_proto_flux_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionResponse) ProtoMessage() {}

func (x *ExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flux_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionResponse.ProtoReflect.Descriptor instead.
func (*ExecutionResponse) Descriptor() ([]byte, []int) {
	return file_proto_flux_proto_rawDescGZIP(), []int{5}
}

func (x *ExecutionResponse) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ExecutionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecutionResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_flux_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flux_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_flux_proto_rawDescGZIP(), []int{6}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_flux_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flux_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_flux_proto_rawDescGZIP(), []int{7}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_proto_flux_proto protoreflect.FileDescriptor

const file_proto_flux_proto_rawDesc = "" +
	"\n" +
	"\x10proto/flux.proto\x12\x04flux\"[\n" +
	"\x11DeploymentPackage\x12#\n" +
	"\rfunction_name\x18\x01 \x01(\tR\ffunctionName\x12!\n" +
	"\fcode_archive\x18\x02 \x01(\fR\vcodeArchive\"C\n" +
	"\rDeploymentAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xab\x01\n" +
	"\x0eFunctionConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\ahandler\x18\x02 \x01(\tR\ahandler\x12%\n" +
	"\x0ecpu_millicores\x18\x03 \x01(\x05R\rcpuMillicores\x12\x1b\n" +
	"\tmemory_mb\x18\x04 \x01(\x03R\bmemoryMb\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\"A\n" +
	"\vFunctionAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"M\n" +
	"\x10ExecutionRequest\x12#\n" +
	"\rfunction_name\x18\x01 \x01(\tR\ffunctionName\x12\x14\n" +
	"\x05input\x18\x02 \x01(\fR\x05input\"b\n" +
	"\x11ExecutionResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\fR\x06output\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x03R\n" +
	"durationMs\"\x14\n" +
	"\x12HealthCheckRequest\"I\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion2\x93\x02\n" +
	"\fAgentService\x12;\n" +
	"\x10RegisterFunction\x12\x14.flux.FunctionConfig\x1a\x11.flux.FunctionAck\x12>\n" +
	"\x0eDeployFunction\x12\x17.flux.DeploymentPackage\x1a\x13.flux.DeploymentAck\x12B\n" +
	"\x0fExecuteFunction\x12\x16.flux.ExecutionRequest\x1a\x17.flux.ExecutionResponse\x12B\n" +
	"\vHealthCheck\x12\x18.flux.HealthCheckRequest\x1a\x19.flux.HealthCheckResponseB\fZ\n" +
	"flux/protob\x06proto3"

var (
	file_proto_flux_proto_rawDescOnce sync.Once
	file_proto_flux_proto_rawDescData []byte
)

func file_proto_flux_proto_rawDescGZIP() []byte {
	file_proto_flux_proto_rawDescOnce.Do(func() {
		file_proto_flux_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_flux_proto_rawDesc), len(file_proto_flux_proto_rawDesc)))
	})
	return file_proto_flux_proto_rawDescData
}

var file_proto_flux_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_flux_proto_goTypes = []any{
	(*DeploymentPackage)(nil),   // 0: flux.DeploymentPackage
	(*DeploymentAck)(nil),       // 1: flux.DeploymentAck
	(*FunctionConfig)(nil),      // 2: flux.FunctionConfig
	(*FunctionAck)(nil),         // 3: flux.FunctionAck
	(*ExecutionRequest)(nil),    // 4: flux.ExecutionRequest
	(*ExecutionResponse)(nil),   // 5: flux.ExecutionResponse
	(*HealthCheckRequest)(nil),  // 6: flux.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 7: flux.HealthCheckResponse
}
var file_proto_flux_proto_depIdxs = []int32{
	2, // 0: flux.AgentService.RegisterFunction:input_type -> flux.FunctionConfig
	0, // 1: flux.AgentService.DeployFunction:input_type -> flux.DeploymentPackage
	4, // 2: flux.AgentService.ExecuteFunction:input_type -> flux.ExecutionRequest
	6, // 3: flux.AgentService.HealthCheck:input_type -> flux.HealthCheckRequest
	3, // 4: flux.AgentService.RegisterFunction:output_type -> flux.FunctionAck
	1, // 5: flux.AgentService.DeployFunction:output_type -> flux.DeploymentAck
	5, // 6: flux.AgentService.ExecuteFunction:output_type -> flux.ExecutionResponse
	7, // 7: flux.AgentService.HealthCheck:output_type -> flux.HealthCheckResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_flux_proto_init() }
func file_proto_flux_proto_init() {
	if File_proto_flux_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_flux_proto_rawDesc), len(file_proto_flux_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_flux_proto_goTypes,
		DependencyIndexes: file_proto_flux_proto_depIdxs,
		MessageInfos:      file_proto_flux_proto_msgTypes,
	}.Build()
	File_proto_flux_proto = out.File
	file_proto_flux_proto_goTypes = nil
	file_proto_flux_proto_depIdxs = nil
}
